Tools page
Plootie/SIT.Manager.Avalonia pull request #22
Opened 2024-02-17 12:35 UTC by artehe

The tools page implementation

2024-02-20 19:45 UTC, artehe commented
I think this is done, or at least the first version of it. Tonnes of room for improvement but with the testing I did it seemed to do the job right.

2024-02-21 05:55 UTC, Plootie requested changes
Amazing work! Most of the stuff I commented on was small and somewhat nitpicky. Remind me to never do a code review on a 2000+ line PR ever again...

2024-02-21 05:55 UTC, Plootie commented on SIT.Manager.Avalonia/Services/InstallerService.cs
> +            }
Your thoughts on making this a static string dictionary with a TryGet and an if statement to cover exit code 10?

2024-02-21 05:55 UTC, Plootie commented on SIT.Manager.Avalonia/Services/InstallerService.cs
> +                }
`providetLinks.TryAdd`?

2024-02-21 05:55 UTC, Plootie commented on SIT.Manager.Avalonia/Services/InstallerService.cs
> +                _configService.Save();
This will need changed once #31 is merge

2024-02-21 05:55 UTC, Plootie commented on SIT.Manager.Avalonia/Services/InstallerService.cs
> +                    File.Delete(sitReleaseZipPath);
See previous comments

2024-02-21 05:55 UTC, Plootie commented on SIT.Manager.Avalonia/Services/InstallerService.cs
> +                    _configService.UpdateConfig(config);
See previous

2024-02-21 05:55 UTC, Plootie commented on SIT.Manager.Avalonia/Services/InstallerService.cs
> +                _configService.UpdateConfig(config);
See previous (sorry!)

2024-02-21 05:55 UTC, Plootie commented on SIT.Manager.Avalonia/Services/TarkovClientService.cs
> +                }
See my previous comment about the aki clear cache

2024-02-21 05:55 UTC, Plootie commented on SIT.Manager.Avalonia/Services/TarkovClientService.cs
> +                }
See previous regarding this

2024-02-21 05:55 UTC, Plootie commented on SIT.Manager.Avalonia/ViewModels/Dialogs/SelectServerVersionDialogViewModel.cs
> +                using (HttpClient httpClient = new() {
See my previous comments about `HttpClient`

2024-02-21 05:55 UTC, Plootie commented on SIT.Manager.Avalonia/ViewModels/Dialogs/SelectServerVersionDialogViewModel.cs
> +                using (HttpClient httpClient = new() {
See my previous comments about `HttpClient`

2024-02-21 05:55 UTC, Plootie commented on SIT.Manager.Avalonia/ViewModels/Dialogs/SelectSitVersionDialogViewModel.cs
> +                using (HttpClient httpClient = new() {
See previous comments about `HttpClient`

2024-02-21 05:55 UTC, Plootie commented on SIT.Manager.Avalonia/ViewModels/Dialogs/SelectSitVersionDialogViewModel.cs
> +                        release.tag_name = release.name + " - Tarkov Version: " + releasePatch;
Could we replace this with `string.Format`?

2024-02-21 05:55 UTC, Plootie commented on SIT.Manager.Avalonia/ViewModels/LocationEditorViewModel.cs
> +                }
Possible use for a dictionary?

2024-02-21 09:29 UTC, artehe commented
> Amazing work! Most of the stuff I commented on was small and somewhat nitpicky. Remind me to never do a code review on a 2000+ line PR ever again...

Haha sorry, I should have broken it down into smaller pieces to make it easier to read through but just wanted to get it all done.

2024-02-21 09:50 UTC, artehe commented on SIT.Manager.Avalonia/Models/BaseLocation.cs
> +﻿using System.Collections.Generic;
Not particularly, copy and pasting this initially to get it working is fine I think. I'd rather not have to write more data classes like this in the future though.

I've never properly dabbled with source generators, but like you say it does seem like this would be a good use case. Although I imagine the time it would take to get it working is something for a future PR

2024-02-21 09:53 UTC, artehe commented on SIT.Manager.Avalonia/Services/AkiServerService.cs
> +                }
Shoulda probably seen this initially, can just replace the whole thing with `Directory.Delete(serverCachePath, true);` and gt the same result

2024-02-21 10:01 UTC, artehe commented on SIT.Manager.Avalonia/Services/InstallerService.cs
> +                }
Just to double check renamed BattlEye folder to BattlEye-BAK and then it throws this without the Directory.Exists check: System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'C:\SIT\game\BattlEye'.'

So this has to stay unfortunately, although they may still be a way of making it look nicer.

2024-02-21 10:11 UTC, artehe commented on SIT.Manager.Avalonia/Services/InstallerService.cs
> +            using (HttpClient httpClient = new() {
Sure

2024-02-21 10:12 UTC, artehe commented on SIT.Manager.Avalonia/Services/InstallerService.cs
> +                _configService.Save();
That and probably a tonne of other places.

2024-02-21 10:16 UTC, artehe commented on SIT.Manager.Avalonia/ViewModels/Dialogs/SelectServerVersionDialogViewModel.cs
> +                using (HttpClient httpClient = new() {
This and the SelectSitVersionDialog are really similar like almost identical, so I will probably make these use a single shared dialog and just load the necessary data in to start with.

2024-02-21 10:30 UTC, artehe commented on SIT.Manager.Avalonia/Services/InstallerService.cs
> +            }
I like it

2024-02-21 10:41 UTC, artehe commented on SIT.Manager.Avalonia/Services/InstallerService.cs
> +                }
You're right, just old habbits

2024-02-21 10:43 UTC, artehe commented on SIT.Manager.Avalonia/ViewModels/Dialogs/SelectSitVersionDialogViewModel.cs
> +                        release.tag_name = release.name + " - Tarkov Version: " + releasePatch;
changed to be $"{release.name} - Tarkov Version: {releasePatch}" as that should work the same.

2024-02-21 10:50 UTC, artehe commented on SIT.Manager.Avalonia/ViewModels/LocationEditorViewModel.cs
> +                }
Yep definitely

2024-02-21 10:55 UTC, artehe commented on SIT.Manager.Avalonia/Services/InstallerService.cs
> +                    var patcherTo = releaseName.Split(" to ")[1];
I've made it a bit better, but I do agree it's not great.

2024-02-21 21:09 UTC, Plootie approved these changes
All looks good :3 Anything else we don't like we can always change later

2024-02-21 21:17 UTC, Plootie commented on SIT.Manager.Avalonia/Models/BaseLocation.cs
> +        public int Area { get; set; }
Switching this to a float fixes factory day crashing the manaher

2024-02-21 21:32 UTC, merged